// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalesWebMvc.Data;

namespace SalesWebMvc.Migrations
{
    [DbContext(typeof(SalesWebMvcContext))]
    [Migration("20190203215746_SalesEmpresasEDepartamentos")]
    partial class SalesEmpresasEDepartamentos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SalesWebMvc.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<bool>("Deletado");

                    b.Property<DateTime>("DeletadoData");

                    b.Property<string>("Descricao");

                    b.Property<int>("EmpresaId");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique();

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("SalesWebMvc.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("CEP");

                    b.Property<string>("CNPJ");

                    b.Property<DateTime>("DataAbertura");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Database");

                    b.Property<bool>("Deletado");

                    b.Property<DateTime>("DeletadoData");

                    b.Property<string>("Email");

                    b.Property<string>("Fantasia");

                    b.Property<string>("IE");

                    b.Property<string>("RazaoSocial");

                    b.Property<string>("Website");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("SalesWebMvc.Models.Departamento", b =>
                {
                    b.HasOne("SalesWebMvc.Models.Empresa", "Empresa")
                        .WithOne("Departamento")
                        .HasForeignKey("SalesWebMvc.Models.Departamento", "EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
